image: conanio/gcc7

before_script:
  - sudo apt update
  - sudo apt install -y lcov doxygen
  - export CONAN_V2_MODE=1
  - cd build

build:
  script:
    - conan create .. umrob/testing
    - cmake -DENABLE_TESTING=ON -DENABLE_CPPCHECK=ON -DENABLE_LCOV=ON ..
    - cmake --build . --parallel
    - ctest
    - cmake --build . --target coverage
